apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
  namespace: prod-ns
spec:
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      labels:
        app: log-agent
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "while true; do echo logging; sleep 10; done"]
